#!/usr/bin/env python3

from distutils.dir_util import copy_tree
import shutil
import os

src_dir = 'test'
dst_dir = '.'

os.system(f"composer create-project roots/bedrock {src_dir}")

copy_tree(src_dir, dst_dir)

with open(".gitignore", "a") as f:
    f.write("tmp")

shutil.rmtree(src_dir)
os.remove("bootstrap")

