version: '3.3'

services:
  wordpress:
    depends_on:
      - db
      - memcached
    image: docker.io/bitpoke/wordpress-runtime:bedrock-php-8.1
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wp_bedrock
      DB_PREFIX: wp_
      MEMCACHED_HOST: memcached:11211
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080/wp
      WP_ENV: development

  db:
    image: percona:5.7
    restart: always
    volumes:
      - ./tmp/percona:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_bedrock
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  memcached:
    image: memcached:1.5

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
